"use client";
import { useRouter } from "next/navigation";
import LoginForm from "../components/login/LoginForm";
import { useState } from "react";


export default function LoginPage() {
  
  const [ registrationCode, setRegistrationCode ] = useState("");
  const [ email, setEmail ] = useState("");
  const [ password, setPassword ] = useState("");
  const [ confirmPassword, setConfirmPassword ] = useState("");
  const [ firstName, setFirstName ] = useState("");
  const [ lastName, setLastName ] = useState("");
  
  const router = useRouter();

  const verifyRequiredFields = () => {
    if (
      registrationCode === "" || 
      email === "" || 
      password === "" || 
      confirmPassword === "" || 
      firstName === "" ||
      lastName === "" 
    ) {
      alert("Please Fill out all fields before continuing.");
      return false;
    }

    if ( password !== confirmPassword ) {
      alert ("Your passwords do not match.");
      return false;
    }

    return true;
  }

  const submitRegistration = () => {}
  

  return (
    <div className="min-h-screen flex flex-col">
      <div className="flex-1 flex items-center justify-center pb-40">
        <fieldset className="fieldset bg-base-200 border-base-300 rounded-box w-xs border p-4">
          <legend className="fieldset-legend">Register</legend>

          <label className="label">Registration Code</label>
          <input 
            type="text" 
            className="input" 
            placeholder="Registration Code"
            value={registrationCode} 
            onChange={(e) => setRegistrationCode(e.target.value)}
          />
          {/* Use API to verify code and get information for the user (name, company public key, email, etc...) */}
          <button className="btn btn-neutral mt-4">Verify Code</button>
          
          {/* The email may be auto generated by the registration code */}
          <label className="label">Email</label>
          <input 
            type="email" 
            className="input" 
            placeholder="Email" 
            value={email} 
            onChange={(e) => setEmail(e.target.value)}
          />
          
          <label className="label">Password</label>
          <input 
            type="password" 
            className="input" 
            placeholder="Password" 
            value={password} 
            onChange={(e) => setPassword(e.target.value)}
          />
          
          <label className="label">Confirm Password</label>
          <input 
            type="password" 
            className={`input 
              ${password !== confirmPassword && password !== "" ? "border-red-500" : ""
            }`}
            placeholder="Confirm Password" 
            value={confirmPassword} 
            onChange={(e) => setConfirmPassword(e.target.value)}
          />
          
          <label className="label">First Name</label>
          <input 
            className="input" 
            placeholder="Email" 
            value={firstName} 
            onChange={(e) => setFirstName(e.target.value)}
          />

          <label className="label">Last Name</label>
          <input 
            className="input" 
            placeholder="Email" 
            value={lastName} 
            onChange={(e) => setLastName(e.target.value)}
          />

          <button className="btn btn-neutral mt-4"
            onClick={ () => verifyRequiredFields() ? submitRegistration : null }

        >
            Confirm Registration
          </button>

        </fieldset>
        
      </div>
    </div>
  );
}