    "use client";
    import { useRouter } from "next/navigation";

    import { useContext, useEffect, useState } from "react";
    import { Context } from "../global/Context";
    import { RegistrationTokenAPI } from "../utils/apiclient";



    export default function RegisterForm() {
    
    const [ registrationToken, setRegistrationToken ] = useState("");
    const [ email, setEmail ] = useState("");
    const [ password, setPassword ] = useState("");
    const [ confirmPassword, setConfirmPassword ] = useState("");
    const [ firstName, setFirstName ] = useState("");
    const [ lastName, setLastName ] = useState("");
    const [ hasSubmittedToken, setHasSubmittedToken ] = useState<boolean>(false)

    const { sessionToken } = useContext(Context);
    const router = useRouter();

    useEffect(() => {  
        if(sessionToken) {
            console.log("Already logged in, redirecting to home.");
            router.push("/home");
        }
    
    },[])

    const verifyRequiredFields = () => {
        if (
            registrationToken === "" || 
            email === "" || 
            password === "" || 
            confirmPassword === "" || 
            firstName === "" ||
            lastName === "" 
        ) {
            alert("Please Fill out all fields before continuing.");
            return false;
        }

        if ( password !== confirmPassword ) {
            alert ("Your passwords do not match.");
            return false;
        }

        return true;
    }

    const submitRegistrationToken = () => {
        /*
        RegistrationTokenAPI.getTokenValues(registrationToken)
            .then( (response) => {
                setEmail(response.email);
                setHasSubmittedToken(true);
            })
            .catch( (error) => {
                console.error("Error using token:", error);
                alert("Failed to use registration token.");
            });
        */
        setEmail("testemail@test.com");
        setHasSubmittedToken(true);
    };

    const clearFields = () => {
        setRegistrationToken("");
        setEmail("");
        setPassword("");
        setConfirmPassword("");
        setFirstName("");
        setLastName("");
        setHasSubmittedToken(false);
    };

    const registerButton = () => {
        // API
    };
    

    return (
        <div className="min-h-screen flex flex-col">
            <div className="flex justify-center pb-40">
                <fieldset className="fieldset bg-base-200 border-base-300 rounded-box w-xs border p-4">
                <legend className="fieldset-legend">Register</legend>

                <label className="label">Registration Code</label>
                <input 
                    type="text" 
                    className="input" 
                    placeholder="Registration Code"
                    value={registrationToken} 
                    disabled={hasSubmittedToken}
                    onChange={(e) => setRegistrationToken(e.target.value)}
                />
                {/* Use API to verify code and get information for the user (name, company public key, email, etc...) */}
                {!hasSubmittedToken ?
                    <button className="btn btn-neutral mt-4" onClick={submitRegistrationToken}>Verify Code</button> :
                    <button className="btn btn-neutral mt-4" onClick={clearFields}>Try New Code</button>
                }
                
                {/* The email may be auto generated by the registration code */}
                {hasSubmittedToken && (
                    <>
                        <label className="label">Email</label>
                        <input 
                            type="email" 
                            className="input" 
                            placeholder="Email" 
                            value={email} 
                            disabled
                            onChange={(e) => setEmail(e.target.value)}
                        />
                        
                        <label className="label">Password</label>
                        <input 
                            type="password" 
                            className="input" 
                            placeholder="Password" 
                            value={password} 
                            onChange={(e) => setPassword(e.target.value)}
                        />
                        
                        <label className="label">Confirm Password</label>
                        <input 
                            type="password" 
                            className={`input 
                            ${password !== confirmPassword && password !== "" ? "border-red-500" : ""
                            }`}
                            placeholder="Confirm Password" 
                            value={confirmPassword} 
                            onChange={(e) => setConfirmPassword(e.target.value)}
                        />
                        
                        <label className="label">First Name</label>
                        <input 
                            className="input" 
                            placeholder="First Name" 
                            value={firstName} 
                            onChange={(e) => setFirstName(e.target.value)}
                        />

                        <label className="label">Last Name</label>
                        <input 
                            className="input" 
                            placeholder="Last Name" 
                            value={lastName} 
                            onChange={(e) => setLastName(e.target.value)}
                        />

                        <button className="btn btn-neutral mt-4"
                            disabled={ verifyRequiredFields! ? false : true }
                            onClick={ () => verifyRequiredFields() ? registerButton : null }
                        >
                            Confirm Registration
                        </button>
                    </>
                )}
                

                </fieldset>
                
            </div>
        </div>
    );
}